version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: spesen-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spesen
    ports:
      - "5436:5432"
    volumes:
      - postgres_data_spesen:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_spesen:
    driver: local
